"""
Generate synthetic AIS history for the simulation ships.

ships.json holds identity and current position only. The pipeline's AIS step
needs position *over time* to ask which vessels were near the estimated origin
during the estimated release window, so that history lives here in its own file.

Tracks are built relative to the demo origin so distances are exact and the
scenario is reproducible: each ship is placed at a chosen distance from the
origin at the reference time, then moved along its heading.

Run from the backend/ directory:
    python scripts/generate_ais_history.py
"""
import json
import sys
from datetime import datetime, timedelta, timezone
from math import cos, radians, sin

from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND))

from core.config import SIMULATION_DIR
from services.data_store import get_pipeline_demo
from services.drift_model import estimate_origin
from services.simulation_service import get_snapshot_data
from services.spill_detection import characterize, scan_snapshot

KM_PER_DEG_LAT = 110.574
KT_TO_KMH = 1.852

DATE = datetime(2026, 8, 15, 9, 0, tzinfo=timezone.utc)
STEP_MIN = 15
STEPS = 13                      # 09:00 -> 12:00
REF_TIME = datetime(2026, 8, 15, 10, 30, tzinfo=timezone.utc)   # release-window midpoint


def km_per_deg_lon(lat):
    return 111.320 * cos(radians(lat))


# Each ship: how far it passes from the origin at REF_TIME, on what bearing from
# the origin, its course/speed, and any behavioural event.
SHIPS = [
    # id,      ca_km, ca_bearing, heading, speed_kt, event
    ("ship1", 48.0, 310, 145, 12.5, None),
    ("ship2", 2.0, 40, 202, 9.8, None),
    ("ship3", 33.0, 120, 88, 13.2, None),
    ("ship4", 5.0, 200, 271, 16.4, "turn_and_slow"),
    ("ship5", 7.0, 75, 318, 7.6, "minor_slowdown"),
]

# ship4 loses AIS across these steps (index into the timeline).
DARK_STEPS = {6, 7}


def _relative_track(heading, speed_kt, event):
    """Track in km relative to its own start, before translation."""
    points, x, y = [], 0.0, 0.0
    for i in range(STEPS):
        t = DATE + timedelta(minutes=STEP_MIN * i)
        hdg, spd = heading, speed_kt
        if event == "turn_and_slow" and t >= REF_TIME:
            hdg, spd = (heading + 120) % 360, 3.1
        elif event == "minor_slowdown" and t >= REF_TIME:
            spd = speed_kt * 0.72
        points.append({"time": t, "x": x, "y": y, "speed_kt": round(spd, 1),
                       "heading": round(hdg, 1)})
        leg = spd * KT_TO_KMH * (STEP_MIN / 60)
        y += leg * cos(radians(hdg))
        x += leg * sin(radians(hdg))
    return points


def build(origin_lat, origin_lon):
    ships = []
    for ship_id, ca_km, ca_bearing, heading, speed_kt, event in SHIPS:
        rel = _relative_track(heading, speed_kt, event)

        # Translate so the position at REF_TIME sits ca_km from the origin.
        ref = next(p for p in rel if p["time"] == REF_TIME)
        target_y = ca_km * cos(radians(ca_bearing))
        target_x = ca_km * sin(radians(ca_bearing))
        dx, dy = target_x - ref["x"], target_y - ref["y"]

        track = []
        for i, p in enumerate(rel):
            if ship_id == "ship4" and i in DARK_STEPS:
                continue  # AIS gap
            lat = origin_lat + (p["y"] + dy) / KM_PER_DEG_LAT
            lon = origin_lon + (p["x"] + dx) / km_per_deg_lon(origin_lat)
            track.append({
                "time": p["time"].strftime("%Y-%m-%dT%H:%M:%SZ"),
                "lat": round(lat, 5),
                "lon": round(lon, 5),
                "speed_kt": p["speed_kt"],
                "heading": p["heading"],
            })
        ships.append({"ship_id": ship_id, "track": track})
    return ships


def main():
    # Anchor the tracks to the origin the pipeline actually computes, so the
    # scenario stays consistent if the drift parameters are retuned.
    demo = get_pipeline_demo()
    snapshot_id = max(demo["snapshot_times"])
    detection = scan_snapshot(get_snapshot_data(snapshot_id))["detections"][0]
    origin = estimate_origin(characterize(detection),
                             demo["snapshot_times"][snapshot_id])
    out = {
        "note": (
            "Synthetic AIS history for the simulation ships. Generated by "
            "scripts/generate_ais_history.py. No real vessel is represented."
        ),
        "interval_minutes": STEP_MIN,
        "origin_reference": {"lat": origin["origin_lat"], "lon": origin["origin_lon"]},
        "ships": build(origin["origin_lat"], origin["origin_lon"]),
    }
    path = SIMULATION_DIR / "ais_history.json"
    path.write_text(json.dumps(out, indent=1))
    print(f"wrote {path} ({len(out['ships'])} ships)")


if __name__ == "__main__":
    main()
